repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort

  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
